### PR TITLE
Remove not needed libplatform dep

### PR DESCRIPTION
**Pull request by hudokkow**

### CODE REVIEW

**Comment by notspiff** [comment]
same. is kodiplatform really needed?

**Comment by hudokkow** [comment]
Good point. It only provides XMLUtils and grep comes out empty.
Hold on these for a few hours and I'll remove it.

Lunch time now!

**Comment by hudokkow** [comment]
Updated.

**Comment by MartijnKaijser** [comment]
seems to break windows builds

**Comment by hudokkow** [comment]
Funny error. We include libXBMC_addon.h that needs dlfcn-win32.h - https://github.com/xbmc/xbmc/blob/master/addons/library.xbmc.addon/libXBMC_addon.h#L38-L42 - but it doesn't find it because we're building an add-on...

@notspiff, your thoughts? Revert or do you see another way?

**Comment by notspiff** [comment]
revert. we should use the one from kodiplatform in core as well eventually.

**Comment by MartijnKaijser** [comment]
Some addons work, some don't so probably need to check the failed ones what the cause is

**Comment by hudokkow** [comment]
The audiodecoder.* add-ons I checked all fail with the same error. I'll have a closer look later.

**Pull request merged**
